spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/descam
    username: postgres
    password: aass1122

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true